# Generated by Django 2.0.7 on 2021-12-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='链接'),
        ),
    ]
