# Generated by Django 3.2 on 2021-12-23 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211221_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='CountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cip', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=20, verbose_name='浏览器')),
                ('resolution', models.CharField(max_length=15, verbose_name='分辨率')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '统计',
                'verbose_name_plural': '统计',
                'db_table': 'chat_count',
            },
        ),
    ]
