# Generated by Django 3.2 on 2021-12-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countuser',
            name='resolution',
        ),
    ]
