# Generated by Django 3.2 on 2021-12-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_highproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='highproblem',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
